<?php
/**
 * @file
 * Code for the Dynamic Example Message Training feature.
 */

include_once 'dynamic_example_message_training.features.inc';

/**
 * Implements hook_comment_insert().
 */
function dynamic_example_message_training_comment_insert($comment) {
  $account = user_load($comment->uid);
  $node = node_load($comment->nid);

  dpm($node);

  $message = message_create('new_comment', array(), $account);
  // Save reference to the node in the node reference field, and the
  // "publish" state (i.e. if the node is published or unpublished).
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_node->set($node);
  $wrapper->field_comment->set($comment);

  $wrapper->save();
}
