<?php

/**
 * @file
 * Populate Exercise content.
 */

/**
 * Implements hook_migrate_api().
 */
function exercise_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'ExerciseCompaniesMigrate',
    'ExerciseEventsMigrate',
    // Users.
    'ExerciseUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
